/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation_tier;

import businesstier.operations;
import com.mysql.jdbc.Statement;
import data_tier.category;
import data_tier.charges;
import java.awt.Graphics;
import java.awt.print.PageFormat;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author sanju
 */
public class chargess extends javax.swing.JFrame {
String stmt;
String con;
    
    public chargess() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        paybtn = new javax.swing.JButton();
        txtrefno = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Category", "IN time", "OUT", "Price per hour", "Total"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 140, 590, 120);

        paybtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        paybtn.setText("Pay");
        paybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paybtnActionPerformed(evt);
            }
        });
        getContentPane().add(paybtn);
        paybtn.setBounds(430, 270, 170, 40);

        txtrefno.setText("Ref No:");
        txtrefno.setName(""); // NOI18N
        getContentPane().add(txtrefno);
        txtrefno.setBounds(280, 70, 180, 30);

        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchbtn);
        searchbtn.setBounds(500, 70, 65, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Car-Availability.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 630, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paybtnActionPerformed

        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        String today = (dateFormat.format(date));

        DateFormat dateFormat2 = new SimpleDateFormat("HH:mm:ss");
        Date date2 = new Date();
        String time = (dateFormat2.format(date2));

        operations o = new operations();
        try {
            int catID = 1;
            // catID=o.Vehicleclassify(file_name);

            ArrayList<category> cat = new ArrayList<category>();
            cat = (o.Searchcategory(catID));
            String name = "";
            double price = 0;
            for (category c : cat) {
                name = c.getCategory();
                price = c.getPrice_per_hour();
            }
            ArrayList<charges> charge = new ArrayList<charges>();
            charges c = new charges();
            c.setCategory(name);
            c.setDate(today);
            c.setINtime(time);
            c.setPrice_per_hour(price);
            charge.add(c);
            int ID = o.Addcharges(charge);
            if (o.Addcharges(charge) != 0) {
                bill2 b = new bill2() {
                    @Override
                    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                    }
                };
//                    String outtime = null;
//                    b.jbout(ID, price, time,outtime, today, catID);
                JOptionPane.showMessageDialog(null, "Succesfully paid!");

            } else {
                JOptionPane.showMessageDialog(null, "Payment Failed!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(CategoryModification.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(image_Processing.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_paybtnActionPerformed

//    public void tableupdate(){
//
//        DefaultTableModel model=(DefaultTableModel) tbl.getModel();
//try{
//
//           
//    String query="SELECT * FROM charges ORDER BY order_num DESC;";
//
//    ResultSet rs = stmt.executeQuery(query);
//    while(rs.next()){
//        String category=rs.getString("category");
//        String INtime=rs.getString("IN Time");
//        String Outtime=rs.getString("Out Time");
//        double price_per_hour=rs.getDouble("Price per hour");
//        double total=rs.getDouble("Total");
//
//      model.addRow(new Object[] {category ,INtime,Outtime,price_per_hour,total});
//
//    }
//}
//catch(Exception e){
//    System.out.print(e);
//}
//}
    
    
    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        int ID = Integer.parseInt(txtrefno.getText());

        if (txtrefno.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Required all fields..");
        } else {
            operations o = new operations();
            ArrayList<charges> charge = new ArrayList<charges>();
            try {
                charge = o.searchcharges(ID);
                if (charge.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Not found..");
                } else {
                    tbl.setColumnSelectionInterval(0, ID);
                }
            } catch (SQLException ex) {
                Logger.getLogger(chargess.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chargess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chargess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chargess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chargess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chargess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton paybtn;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtrefno;
    // End of variables declaration//GEN-END:variables
}
